### ISSUE TITLE
运行 kitti_dataset_example 时只显示了UI但是没有数据

### ISSUE THREAD

**Issue by zxytql** [sunshanlu/SLAM_VIEWER#1]
感谢开源~

## 问题描述
在编译完后，在bin文件夹下执行命令
```
./kitti_dataset_example ~/Documents/KITTI_Odometry/ 06/
```
能正常显示UI窗口，也可以正常拖动，但是没有数据输出。
![image](https://github.com/user-attachments/assets/a75e1d57-2f69-4ee8-8c2c-22c42dae871d)

我的 `~/Documents/KITTI_Odometry/`的目录架构如下：
```
zxx@ubuntu:~/Documents/KITTI_Odometry$ tree -d
.
├── results
├── sequences
│   └── 06
│       ├── image_0
│       └── image_1
└── velodyne
    └── sequences
        └── 06
            └── velodyne

9 directories
```
请问是哪一步出了问题？ 如果需要更多信息，我可以补充 :)

**Comment by sunshanlu** [comment]
![image](https://github.com/user-attachments/assets/1b1a3f2a-30c9-4f64-9eeb-d33b973e2262)
使用`./kitti_dataset_example ~/Documents/KITTI_Odometry 06`，不要添加反斜杠

**Comment by zxytql** [comment]
@sunshanlu 谢谢回复。我尝试了不加反斜杠的命令
```shell
./kitti_dataset_example ~/Documents/KITTI_Odometry 06
```
会报如下错误：
```shell
zxx@ubuntu:~/work/SLAM_VIEWER/bin$ ./kitti_dataset_example ~/Documents/KITTI_Odometry/ 06
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
已放弃 (核心已转储)
```

**Comment by sunshanlu** [comment]
我一开始以为是你在执行命令的时候，在路径的后面添加了反斜杠造成的，但是我使用了和你相同的命令 
`./kitti_dataset_example /media/lucky-lu/新加卷/Dataset/SLAM/KITTI/ 06` 
在我电脑上，代码是正常执行的。
我的建议是：
1.将路径部分的最后的反斜杠去掉，使用`./kitti_dataset_example ~/Documents/KITTI_Odometry 06` 而不是`./kitti_dataset_example ~/Documents/KITTI_Odometry/ 06`，再次运行一下看看是否正常。
2.如果还是出现length_error,你不妨使用debug模式，排查一下到底是哪部分的操作使得vector出现了length_error。

这张图片是 06 在我电脑上运行的结果。
![image](https://github.com/user-attachments/assets/019b42ee-64be-4ca4-a3ba-7fdd5a1e317e)

**Comment by zxytql** [comment]
@sunshanlu 谢谢回复。我已经解决了这个问题。
问题出现在读取点云文件。我点云文件的命名为`0000000000.bin`，这里有10位数，但在读取的代码中：
```C
ss_id << std::setw(6) << std::setfill('0') << frame_id_++;
```
读取的是6位数的文件。因此导致变量`num_element`达到了上限。

![image](https://github.com/user-attachments/assets/d5ac201b-3211-46d3-b239-132e0ef665e8)

如果将读取的代码修改为
```
ss_id << std::setw(10) << std::setfill('0') << frame_id_++;
```
则又会导致读取图像出错，因为图像的命名是`000000.png`，是一个6位数。

为此我写了一个python脚本，用于修改文件夹内的文件名字：
```python
import os
import sys

directory = sys.argv[1]

def rename_files(directory):
    for filename in os.listdir(directory):
        if filename.endswith('.bin') and len(filename) == 14:  # 10位名字 + '.bin'

            new_name = str(int(filename[:10])) 
            new_name = new_name.zfill(6) + '.bin' 
            
            old_path = os.path.join(directory, filename)
            new_path = os.path.join(directory, new_name)
            
            os.rename(old_path, new_path)
            print(f'Renamed {filename} to {new_name}')

rename_files(directory)

```
经修改后，执行命令
```shell
./kitti_dataset_example ~/Documents/KITTI_Odometry 06
```
或者
```shell
./kitti_dataset_example ~/Documents/KITTI_Odometry/ 06
```
都是可以的。
![image](https://github.com/user-attachments/assets/65140f56-0aa3-48b1-b8e7-adfa42c1c431)
